# Stage 1: Build the React application
FROM node:20-alpine AS build
WORKDIR /app

# Set build arguments
ARG VITE_SCOPE_URL
ARG VITE_REGISTRY_URL
ARG VITE_INTERNAL_ASSETS_URL
ARG VITE_INTERNAL_SCOPE_URL
ARG VITE_RENDER_URL
ARG VITE_DASHBOARD_URL
ARG VITE_REPORTER_URL
ARG VITE_DIRECTOR_URL
ARG VITE_ASSETS_URL

# Pass build arguments as environment variables
ENV VITE_SCOPE_URL=$VITE_SCOPE_URL
ENV VITE_REGISTRY_URL=$VITE_REGISTRY_URL
ENV VITE_INTERNAL_ASSETS_URL=$VITE_INTERNAL_ASSETS_URL
ENV VITE_INTERNAL_SCOPE_URL=$VITE_INTERNAL_SCOPE_URL
ENV VITE_RENDER_URL=$VITE_RENDER_URL
ENV VITE_DASHBOARD_URL=$VITE_DASHBOARD_URL
ENV VITE_REPORTER_URL=$VITE_REPORTER_URL
ENV VITE_DIRECTOR_URL=$VITE_DIRECTOR_URL
ENV VITE_ASSETS_URL=$VITE_ASSETS_URL

COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Stage 2: Serve the React application using Nginx
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
